{
 "title": "API Gateway",
 "time": { "from": "2025-10-26T09:35:44.634Z", "to": "2025-10-26T15:37:48.706Z" },
 "panels": [
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"api-gateway\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{job=\"api-gateway\", status=~\"5..\"}[1m]))\r\n /\r\nsum(rate(http_server_requests_seconds_count{job=\"api-gateway\"}[1m]))\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"api-gateway\"}[1m])) by (le))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"api-gateway\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}