{
 "title": "Patient Service",
 "time": { "from": "2025-10-26T09:38:38.622Z", "to": "2025-10-26T15:40:27.444Z" },
 "panels": [
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"patient-service\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{job=\"patient-service\", status=~\"5..\"}[1m]))\r\n /\r\nsum(rate(http_server_requests_seconds_count{job=\"patient-service\"}[1m]))\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"patient-service\"}[1m])) by (le))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"patient-service\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}