server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/clinic_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-me-please-2025}
    issuer: clinic-booking-app
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 7
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  mail:
    from: ${MAIL_FROM:no-reply@clinic.com}

management:
  endpoints:
    web:
      exposure:
        include: health,info
