server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    active: dev

# Redis configuration
logging:
  level:
    org.springframework.data.redis: DEBUG

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus # Access via /actuator/*
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: api-gateway