-- Fix password hash for seed accounts
-- The original BCrypt hash from online tool was not compatible with Spring BCryptPasswordEncoder
-- This hash was generated by the auth-service itself for password: Test@123

UPDATE users SET password_hash = '$2a$10$Kexw2O3YU7t1RlhE.I3mq.VlP5GXtQCscJwRMgawe3twDM40Anct6' 
WHERE email IN (
  -- Admin accounts
  'admin1@clinic.com', 'admin2@clinic.com', 'admin@clinic.com',
  -- Doctor accounts
  'doctor.cardio@clinic.com', 'doctor.derma@clinic.com', 'doctor.neuro@clinic.com',
  'doctor.pedia@clinic.com', 'doctor.ortho@clinic.com', 'doctor.eye@clinic.com',
  'doctor.ent@clinic.com', 'doctor.gastro@clinic.com', 'doctor.psych@clinic.com',
  'doctor.general@clinic.com',
  -- Patient accounts
  'patient1@gmail.com', 'patient2@gmail.com', 'patient3@gmail.com',
  'patient4@gmail.com', 'patient5@gmail.com', 'patient6@gmail.com',
  'patient7@gmail.com', 'patient8@gmail.com', 'patient9@gmail.com',
  'patient10@gmail.com'
);
