ALTER TABLE oauth_accounts
    ADD COLUMN IF NOT EXISTS full_name VARCHAR(150),
    ADD COLUMN IF NOT EXISTS given_name VARCHAR(150),
    ADD COLUMN IF NOT EXISTS family_name VARCHAR(150),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS picture_url VARCHAR(512),
    ADD COLUMN IF NOT EXISTS locale VARCHAR(32),
    ADD COLUMN IF NOT EXISTS profile JSONB;

