version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: auth_postgres
    environment:
      POSTGRES_DB: clinic_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - auth_pg_data:/var/lib/postgresql/data
    networks:
      - auth-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/clinic_auth
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=clinic-booking-app-secret-key-2025-secure!!
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      # Dev overrides: disable Flyway in-container (workaround for driver/DB compatibility)
      - SPRING_FLYWAY_ENABLED=false
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # Pass JVM properties early so Flyway is disabled before auto-configuration
      - JAVA_OPTS=-Dspring.flyway.enabled=false -Dspring.jpa.hibernate.ddl-auto=update
      # Disable mail health check in dev so actuator health returns UP without mail creds
      - MANAGEMENT_HEALTH_MAIL_ENABLED=false
    depends_on:
      - postgres
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  auth_pg_data:
