services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: clinic_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clinic_auth"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/clinic_auth
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      # JVM sẽ tự lấy JAVA_TOOL_OPTIONS
      JAVA_TOOL_OPTIONS: >
        -Dspring.flyway.enabled=true
        -Dspring.jpa.hibernate.ddl-auto=none
    ports:
      - "8081:8081"

volumes:
  pgdata_auth:
