services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinic
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinic -d clinic"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata_patient:/var/lib/postgresql/data
    
    ports:
      - "5434:5432"

  patient-service:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clinic
      SPRING_DATASOURCE_USERNAME: clinic
      SPRING_DATASOURCE_PASSWORD: clinic
    ports:
      - "8082:8080"

volumes:
  pgdata_patient:

